# Generated by Django 5.2.3 on 2025-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('diploma', 'Diploma'), ('graduation', 'Graduation'), ('masters', 'Masters'), ('phd', 'PhD'), ('postdoc', 'Post Doc')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='result',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D')], max_length=2, null=True),
        ),
    ]
