# Generated by Django 5.2.4 on 2025-07-29 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='result',
        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('diploma', 'Diploma'), ('graduation', 'Graduation'), ('masters', 'Masters'), ('phd', 'PhD'), ('postdoc', 'Post Doc')], max_length=20)),
                ('result', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D')], max_length=2)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
