# Generated by Django 5.2.4 on 2025-07-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalqualification',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='educationalqualification',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
